services:
  - type: web
    name: course-inventory
    env: dotnet
    plan: free
    buildCommand: dotnet publish CourseInventory.Web/CourseInventory.Web.csproj -c Release -o out
    startCommand: dotnet out/CourseInventory.Web.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: Authentication__Google__ClientId
        sync: false
      - key: Authentication__Google__ClientSecret
        sync: false
      - key: Authentication__Facebook__AppId
        sync: false
      - key: Authentication__Facebook__AppSecret
        sync: false
      - key: Cloudinary__CloudName
        sync: false
      - key: Cloudinary__ApiKey
        sync: false
      - key: Cloudinary__ApiSecret
        sync: false
