using System.Globalization;

namespace CourseInventory.Web.Services;

public interface IUiTextService
{
    string this[string key] { get; }
}

public class UiTextService : IUiTextService
{
    private static readonly Dictionary<string, string> English = new(StringComparer.OrdinalIgnoreCase)
    {
        ["Brand"] = "Inventory Studio",
        ["Inventories"] = "Inventories",
        ["Profile"] = "Profile",
        ["Admin"] = "Admin",
        ["SearchPlaceholder"] = "Search inventories, tags, items...",
        ["Light"] = "Light",
        ["Dark"] = "Dark",
        ["Logout"] = "Logout",
        ["Login"] = "Login",
        ["Register"] = "Register",
        ["By"] = "by",
        ["AddItem"] = "Add item",
        ["Items"] = "Items",
        ["Discussion"] = "Discussion",
        ["Settings"] = "Settings",
        ["CustomId"] = "Custom ID",
        ["Fields"] = "Fields",
        ["Access"] = "Access",
        ["Stats"] = "Stats",
        ["Export"] = "Export",
        ["DeleteSelected"] = "Delete selected",
        ["Likes"] = "Likes",
        ["CustomIdPreview"] = "Preview",
        ["Title"] = "Title",
        ["Category"] = "Category",
        ["DescriptionMarkdown"] = "Description Markdown",
        ["ImageUrl"] = "Image URL",
        ["Tags"] = "Tags",
        ["PublicWriteAccess"] = "Public write access",
        ["Save"] = "Save",
        ["AllChangesSaved"] = "All changes saved",
        ["ReadOnly"] = "Read only.",
        ["FixedValue"] = "Fixed value",
        ["Format"] = "Format",
        ["AddElement"] = "Add element",
        ["Remove"] = "Remove",
        ["FieldTitle"] = "Field title",
        ["AddField"] = "Add field",
        ["UserIdAutocomplete"] = "User id from autocomplete endpoint",
        ["Grant"] = "Grant",
        ["ItemsCount"] = "Items",
        ["NumericFields"] = "Numeric fields",
        ["Field"] = "Field",
        ["Min"] = "Min",
        ["Max"] = "Max",
        ["Average"] = "Average",
        ["ExportCsv"] = "Export CSV",
        ["MarkdownMessage"] = "Markdown message",
        ["Send"] = "Send",
        ["PublicWriteAccessValue"] = "Public write access",
        ["HomeEyebrow"] = "SaaS inventory workspace",
        ["HomeHeroTitle"] = "Inventory control that feels fast, shared and precise.",
        ["HomeHeroText"] = "Create inventories, define fields, generate custom IDs, collaborate with your team and export clean operational data.",
        ["NewInventory"] = "New inventory",
        ["GlobalStatistics"] = "Global statistics",
        ["TotalInventories"] = "Total inventories",
        ["TotalItems"] = "Total items",
        ["TotalUsers"] = "Total users",
        ["LatestInventories"] = "Latest inventories",
        ["LatestInventoriesText"] = "Recently updated workspaces across your team.",
        ["SelectRows"] = "Select rows",
        ["ViewAll"] = "View all",
        ["SelectAllLatestInventories"] = "Select all latest inventories",
        ["Owner"] = "Owner",
        ["Updated"] = "Updated",
        ["Unknown"] = "Unknown",
        ["TopFiveByItems"] = "Top 5 by items",
        ["TopFiveByItemsText"] = "Inventories with the most operational weight.",
        ["Inventory"] = "Inventory",
        ["TagCloud"] = "Tag cloud",
        ["TagCloudText"] = "Jump into filtered inventory groups.",
        ["Theme"] = "Theme",
        ["Language"] = "Language",
        ["ProfileWorkspace"] = "Personal workspace",
        ["ProfileSummary"] = "Profile summary",
        ["OwnedInventories"] = "Owned inventories",
        ["WritableInventories"] = "Writable inventories",
        ["AccessibleInventories"] = "Accessible inventories",
        ["MyInventories"] = "My inventories",
        ["MyInventoriesText"] = "Inventories you own and manage.",
        ["InventoriesICanWriteTo"] = "Inventories I can write to",
        ["InventoriesICanWriteToText"] = "Shared workspaces where you have write access.",
        ["LastActivity"] = "Last activity",
        ["FilterTable"] = "Filter table",
        ["NoOwnedInventories"] = "You do not own any inventories yet.",
        ["NoWritableInventories"] = "No shared writable inventories yet.",
        ["InventoryDirectory"] = "Inventory directory",
        ["InventoryDirectoryText"] = "Browse, filter and manage every inventory workspace from one professional table.",
        ["InventoryTableText"] = "Select rows for contextual actions, sort columns and filter by access.",
        ["FilterInventoriesPlaceholder"] = "Filter by title, category or owner",
        ["AllAccess"] = "All access",
        ["Filter"] = "Filter",
        ["BulkActionsHint"] = "Actions apply to the selected rows.",
        ["Selected"] = "selected",
        ["Edit"] = "Edit",
        ["ClearSelection"] = "Clear selection",
        ["NoInventoriesFound"] = "No inventories found",
        ["Previous"] = "Previous",
        ["Next"] = "Next",
        ["InventorySetup"] = "Inventory setup",
        ["InventorySetupText"] = "Start with the essentials. Fields, custom IDs and access can be refined after creation.",
        ["HeadsUp"] = "Heads up",
        ["ConfigureAfterCreation"] = "You can configure fields, custom IDs and access after creation.",
        ["TitleRequired"] = "Title is required.",
        ["ChooseCategory"] = "Choose category",
        ["CategoryRequired"] = "Category is required.",
        ["LivePreview"] = "Live preview",
        ["PreviewAppearsAsYouType"] = "Preview appears as you type.",
        ["ImagePreview"] = "Image preview",
        ["NoImageUrl"] = "No image URL",
        ["InvalidImageUrl"] = "Invalid image URL",
        ["AddTagPlaceholder"] = "Add tag and press Enter",
        ["PublicWriteAccessHelp"] = "Allow all signed-in users to add and edit items.",
        ["Cancel"] = "Cancel",
        ["CreateInventory"] = "Create inventory",
        ["ConfirmDelete"] = "Confirm delete",
        ["ConfirmDeleteSelected"] = "Delete the selected inventories?"
    };

    private static readonly Dictionary<string, string> French = new(StringComparer.OrdinalIgnoreCase)
    {
        ["Brand"] = "Inventaire Studio",
        ["Inventories"] = "Inventaires",
        ["Profile"] = "Profil",
        ["Admin"] = "Admin",
        ["SearchPlaceholder"] = "Rechercher inventaires, tags, articles...",
        ["Light"] = "Clair",
        ["Dark"] = "Sombre",
        ["Logout"] = "Déconnexion",
        ["Login"] = "Connexion",
        ["Register"] = "Inscription",
        ["By"] = "par",
        ["AddItem"] = "Ajouter un article",
        ["Items"] = "Articles",
        ["Discussion"] = "Discussion",
        ["Settings"] = "Paramètres",
        ["CustomId"] = "ID personnalisé",
        ["Fields"] = "Champs",
        ["Access"] = "Accès",
        ["Stats"] = "Statistiques",
        ["Export"] = "Export",
        ["DeleteSelected"] = "Supprimer la sélection",
        ["Likes"] = "Likes",
        ["CustomIdPreview"] = "Aperçu",
        ["Title"] = "Titre",
        ["Category"] = "Catégorie",
        ["DescriptionMarkdown"] = "Description Markdown",
        ["ImageUrl"] = "URL de l'image",
        ["Tags"] = "Tags",
        ["PublicWriteAccess"] = "Accès écriture public",
        ["Save"] = "Enregistrer",
        ["AllChangesSaved"] = "Tous les changements sont enregistrés",
        ["ReadOnly"] = "Lecture seule.",
        ["FixedValue"] = "Texte fixe",
        ["Format"] = "Format",
        ["AddElement"] = "Ajouter un élément",
        ["Remove"] = "Retirer",
        ["FieldTitle"] = "Titre du champ",
        ["AddField"] = "Ajouter un champ",
        ["UserIdAutocomplete"] = "Id utilisateur via autocomplete",
        ["Grant"] = "Autoriser",
        ["ItemsCount"] = "Articles",
        ["NumericFields"] = "Champs numériques",
        ["Field"] = "Champ",
        ["Min"] = "Min",
        ["Max"] = "Max",
        ["Average"] = "Moyenne",
        ["ExportCsv"] = "Exporter CSV",
        ["MarkdownMessage"] = "Message Markdown",
        ["Send"] = "Envoyer",
        ["PublicWriteAccessValue"] = "Accès écriture public",
        ["HomeEyebrow"] = "Espace SaaS d'inventaire",
        ["HomeHeroTitle"] = "Un contrôle d'inventaire rapide, collaboratif et précis.",
        ["HomeHeroText"] = "Créez des inventaires, définissez des champs, générez des ID personnalisés, collaborez avec votre équipe et exportez des données propres.",
        ["NewInventory"] = "Nouvel inventaire",
        ["GlobalStatistics"] = "Statistiques globales",
        ["TotalInventories"] = "Total inventaires",
        ["TotalItems"] = "Total articles",
        ["TotalUsers"] = "Total utilisateurs",
        ["LatestInventories"] = "Derniers inventaires",
        ["LatestInventoriesText"] = "Espaces récemment mis à jour par votre équipe.",
        ["SelectRows"] = "Sélectionner",
        ["ViewAll"] = "Voir tout",
        ["SelectAllLatestInventories"] = "Sélectionner tous les derniers inventaires",
        ["Owner"] = "Propriétaire",
        ["Updated"] = "Mis à jour",
        ["Unknown"] = "Inconnu",
        ["TopFiveByItems"] = "Top 5 par articles",
        ["TopFiveByItemsText"] = "Inventaires avec le plus de volume opérationnel.",
        ["Inventory"] = "Inventaire",
        ["TagCloud"] = "Nuage de tags",
        ["TagCloudText"] = "Accédez rapidement aux groupes filtrés.",
        ["Theme"] = "Thème",
        ["Language"] = "Langue",
        ["ProfileWorkspace"] = "Espace personnel",
        ["ProfileSummary"] = "Résumé du profil",
        ["OwnedInventories"] = "Inventaires possédés",
        ["WritableInventories"] = "Accès écriture",
        ["AccessibleInventories"] = "Inventaires accessibles",
        ["MyInventories"] = "Mes inventaires",
        ["MyInventoriesText"] = "Inventaires que vous possédez et gérez.",
        ["InventoriesICanWriteTo"] = "Inventaires modifiables",
        ["InventoriesICanWriteToText"] = "Espaces partagés où vous avez un accès écriture.",
        ["LastActivity"] = "Dernière activité",
        ["FilterTable"] = "Filtrer le tableau",
        ["NoOwnedInventories"] = "Vous ne possédez encore aucun inventaire.",
        ["NoWritableInventories"] = "Aucun inventaire partagé modifiable pour le moment.",
        ["InventoryDirectory"] = "Répertoire des inventaires",
        ["InventoryDirectoryText"] = "Parcourez, filtrez et gérez tous les espaces d'inventaire depuis un tableau professionnel.",
        ["InventoryTableText"] = "Sélectionnez des lignes pour les actions contextuelles, triez les colonnes et filtrez par accès.",
        ["FilterInventoriesPlaceholder"] = "Filtrer par titre, catégorie ou propriétaire",
        ["AllAccess"] = "Tous les accès",
        ["Filter"] = "Filtrer",
        ["BulkActionsHint"] = "Les actions s'appliquent aux lignes sélectionnées.",
        ["Selected"] = "sélectionné",
        ["Edit"] = "Modifier",
        ["ClearSelection"] = "Effacer la sélection",
        ["NoInventoriesFound"] = "Aucun inventaire trouvé",
        ["Previous"] = "Précédent",
        ["Next"] = "Suivant",
        ["InventorySetup"] = "Configuration de l'inventaire",
        ["InventorySetupText"] = "Commencez par l'essentiel. Les champs, ID personnalisés et accès pourront être affinés après création.",
        ["HeadsUp"] = "Info",
        ["ConfigureAfterCreation"] = "Vous pourrez configurer les champs, ID personnalisés et accès après la création.",
        ["TitleRequired"] = "Le titre est obligatoire.",
        ["ChooseCategory"] = "Choisir une catégorie",
        ["CategoryRequired"] = "La catégorie est obligatoire.",
        ["LivePreview"] = "Aperçu en direct",
        ["PreviewAppearsAsYouType"] = "L'aperçu apparaît pendant la saisie.",
        ["ImagePreview"] = "Aperçu de l'image",
        ["NoImageUrl"] = "Aucune URL d'image",
        ["InvalidImageUrl"] = "URL d'image invalide",
        ["AddTagPlaceholder"] = "Ajouter un tag puis Entrée",
        ["PublicWriteAccessHelp"] = "Autoriser tous les utilisateurs connectés à ajouter et modifier des articles.",
        ["Cancel"] = "Annuler",
        ["CreateInventory"] = "Créer l'inventaire",
        ["ConfirmDelete"] = "Confirmer la suppression",
        ["ConfirmDeleteSelected"] = "Supprimer les inventaires sélectionnés ?"
    };

    public string this[string key]
    {
        get
        {
            var dictionary = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName == "fr" ? French : English;
            return dictionary.TryGetValue(key, out var value) ? value : key;
        }
    }
}
